name: dbt CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  dbt_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Write RSA Key File
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > dbt_demo_project/dbt_key.p8

      - name: Create profiles.yml for CD
        run: |
          mkdir -p ~/.dbt
          echo "dbt_demo_project:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: '${{ secrets.SNOWFLAKE_ACCOUNT }}'
                user: 'SVC_DBT_PROD'
                role: 'SVC_DBT_PROD_ROLE'
                warehouse: 'PROD_TRANSFORM_WH'
                database: 'PROD_BRONZE'
                schema: 'GED'
                threads: 2
                private_key_passphrase: '${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}'
                private_key_path: 'dbt_key.p8'" > ~/.dbt/profiles.yml

      - name: Deploy & Run dbt models in PROD
        run: |
          cd dbt_demo_project
          dbt deps
          dbt debug --target prod
          dbt build --target prod